-- database: shop_system
-- ===================== 部门表 =====================
CREATE TABLE department (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    code varchar(20) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE department IS '部门表';
COMMENT ON COLUMN department.id IS '主键ID-自增';
COMMENT ON COLUMN department.name IS '部门名称';
COMMENT ON COLUMN department.code IS '部门编码（唯一）';
COMMENT ON COLUMN department.created_at IS '创建时间';
COMMENT ON COLUMN department.updated_at IS '更新时间';
COMMENT ON COLUMN department.deleted_at IS '软删除标记，NULL为未删除';
-- 唯一约束：code 在未删除记录中唯一
CREATE UNIQUE INDEX uk_department_code ON department(code) WHERE deleted_at IS NULL;

-- ===================== 岗位表 =====================
CREATE TABLE post (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE post IS '岗位表';
COMMENT ON COLUMN post.id IS '主键ID-自增';
COMMENT ON COLUMN post.name IS '岗位名称';
COMMENT ON COLUMN post.created_at IS '创建时间';
COMMENT ON COLUMN post.updated_at IS '更新时间';
COMMENT ON COLUMN post.deleted_at IS '软删除标记，NULL为未删除';

-- ===================== 员工表 =====================
CREATE TABLE employee (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no varchar(32) NOT NULL,
    post_id bigint,
    dept_id bigint,
    name_cn varchar(64),
    name_th varchar(128),
    name_en varchar(64),
    country varchar(5) NOT NULL,
    phone varchar(32),
    emergency_contact varchar(64),
    emergency_phone varchar(32),
    status smallint DEFAULT 1,
    entry_time timestamptz NOT NULL,
    leave_time timestamptz,
    id_card varchar(64),
    gender smallint DEFAULT 0,
    avatar varchar(512) NOT NULL,
    salary decimal(12,2) DEFAULT 0,
    performance_bonus decimal(12,2) DEFAULT 0,
    subsidy decimal(12,2) DEFAULT 0,
    lark_id varchar(100),
    remark varchar(512),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE employee IS '员工表';
COMMENT ON COLUMN employee.id IS '主键ID-自增';
COMMENT ON COLUMN employee.employee_no IS '员工代号（唯一）';
COMMENT ON COLUMN employee.post_id IS '所属岗位ID（关联post表）';
COMMENT ON COLUMN employee.dept_id IS '所属部门ID（关联department表）';
COMMENT ON COLUMN employee.name_cn IS '中文姓名（中国员工必填）';
COMMENT ON COLUMN employee.name_th IS '泰文姓名（泰国员工必填）';
COMMENT ON COLUMN employee.name_en IS '英文姓名（通用）';
COMMENT ON COLUMN employee.country IS '国家代码，如TH、CN';
COMMENT ON COLUMN employee.phone IS '联系电话';
COMMENT ON COLUMN employee.emergency_contact IS '紧急联系人';
COMMENT ON COLUMN employee.emergency_phone IS '紧急联系电话';
COMMENT ON COLUMN employee.status IS '1-在职，2-离职';
COMMENT ON COLUMN employee.entry_time IS '入职时间';
COMMENT ON COLUMN employee.leave_time IS '离职时间';
COMMENT ON COLUMN employee.id_card IS '身份证号';
COMMENT ON COLUMN employee.gender IS '性别：0-未知，1-男，2-女';
COMMENT ON COLUMN employee.avatar IS '个人图像URL';
COMMENT ON COLUMN employee.salary IS '月薪（底薪），统一泰铢';
COMMENT ON COLUMN employee.performance_bonus IS '绩效';
COMMENT ON COLUMN employee.subsidy IS '补贴';
COMMENT ON COLUMN employee.lark_id IS '员工的Lark User ID';
COMMENT ON COLUMN employee.remark IS '备注';
COMMENT ON COLUMN employee.created_at IS '创建时间';
COMMENT ON COLUMN employee.updated_at IS '更新时间';
COMMENT ON COLUMN employee.deleted_at IS '软删除标记，NULL为未删除';
-- 索引
CREATE UNIQUE INDEX uk_employee_no ON employee(employee_no) WHERE deleted_at IS NULL;
CREATE INDEX idx_employee_post ON employee(post_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_employee_dept ON employee(dept_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_employee_country ON employee(country) WHERE deleted_at IS NULL;
CREATE INDEX idx_employee_lark ON employee(lark_id) WHERE deleted_at IS NULL;

-- ===================== BD人员表 =====================
CREATE TABLE bd_person (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bd_code varchar(10) NOT NULL,
    employee_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE bd_person IS 'BD人员表，存储BD代号与员工的绑定关系';
COMMENT ON COLUMN bd_person.id IS '主键ID-自增';
COMMENT ON COLUMN bd_person.bd_code IS 'BD代号（如BD001），业务唯一';
COMMENT ON COLUMN bd_person.employee_id IS '关联的员工ID（一对一关系）';
COMMENT ON COLUMN bd_person.created_at IS '创建时间';
COMMENT ON COLUMN bd_person.updated_at IS '更新时间';
COMMENT ON COLUMN bd_person.deleted_at IS '软删除标记，NULL为未删除';
CREATE UNIQUE INDEX uk_bd_code ON bd_person(bd_code) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uk_bd_employee ON bd_person(employee_id) WHERE deleted_at IS NULL;

-- ===================== 店铺表 =====================
CREATE TABLE shop (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform smallint NOT NULL DEFAULT 1,
    shop_type smallint NOT NULL DEFAULT 1,
    platform_shop_id varchar(64) NOT NULL,
    shop_name varchar(128) NOT NULL,
    country varchar(5) NOT NULL,
    owner_user_id bigint,
    status smallint NOT NULL DEFAULT 1,
    access_token varchar(512),
    refresh_token varchar(512),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE shop IS '店铺表';
COMMENT ON COLUMN shop.id IS '主键ID-自增';
COMMENT ON COLUMN shop.platform IS '所属平台：1-TikTok，2-Shopee，3-Lazada';
COMMENT ON COLUMN shop.shop_type IS '店铺类型：1-跨境，2-本土';
COMMENT ON COLUMN shop.platform_shop_id IS '平台店铺ID（全局唯一）';
COMMENT ON COLUMN shop.shop_name IS '店铺名称';
COMMENT ON COLUMN shop.country IS '运营国家/站点，如TH、CN';
COMMENT ON COLUMN shop.owner_user_id IS '店铺负责人/运营ID（关联employee表）';
COMMENT ON COLUMN shop.status IS '店铺状态：0-停用，1-正常，2-待审核，3-已冻结';
COMMENT ON COLUMN shop.access_token IS '平台API访问token';
COMMENT ON COLUMN shop.refresh_token IS '平台API刷新token';
COMMENT ON COLUMN shop.created_at IS '创建时间';
COMMENT ON COLUMN shop.updated_at IS '更新时间';
COMMENT ON COLUMN shop.deleted_at IS '软删除标记，NULL为未删除';
CREATE UNIQUE INDEX uk_platform_shop ON shop(platform_shop_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_shop_owner ON shop(owner_user_id) WHERE deleted_at IS NULL;

-- ===================== SKU表 =====================
CREATE TABLE product_sku (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_code varchar(64) NOT NULL,
    sku_type smallint NOT NULL DEFAULT 0,
    sku_name varchar(255) NOT NULL,
    currency varchar(8) DEFAULT 'CNY',
    image_url varchar(512),
    retail_price decimal(12,2) DEFAULT 0,
    cost_price decimal(12,2) DEFAULT 0,
    online_margin decimal(10,2),
    offline_margin decimal(10,2),
    status smallint DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE product_sku IS 'SKU表';
COMMENT ON COLUMN product_sku.id IS '主键ID-自增';
COMMENT ON COLUMN product_sku.sku_code IS 'SKU编码（业务唯一）';
COMMENT ON COLUMN product_sku.sku_type IS '0-单SKU，1-组合SKU';
COMMENT ON COLUMN product_sku.sku_name IS 'SKU名称';
COMMENT ON COLUMN product_sku.currency IS '结算货币（如CNY、THB）';
COMMENT ON COLUMN product_sku.image_url IS '产品图片URL';
COMMENT ON COLUMN product_sku.retail_price IS '零售价';
COMMENT ON COLUMN product_sku.cost_price IS '成本价（仅单SKU填写）';
COMMENT ON COLUMN product_sku.online_margin IS '线上毛利率';
COMMENT ON COLUMN product_sku.offline_margin IS '线下毛利率';
COMMENT ON COLUMN product_sku.status IS '产品状态：0-下架，1-在售';
COMMENT ON COLUMN product_sku.created_at IS '创建时间';
COMMENT ON COLUMN product_sku.updated_at IS '更新时间';
COMMENT ON COLUMN product_sku.deleted_at IS '软删除标记，NULL为未删除';
CREATE UNIQUE INDEX uk_sku_code ON product_sku(sku_code) WHERE deleted_at IS NULL;

-- ===================== 组合SKU明细表 =====================
CREATE TABLE sku_bundle (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bundle_sku_id bigint NOT NULL,
    child_sku_id bigint NOT NULL,
    quantity int NOT NULL DEFAULT 1,
    CONSTRAINT uk_bundle_child UNIQUE (bundle_sku_id, child_sku_id),
    CONSTRAINT fk_bundle_sku FOREIGN KEY (bundle_sku_id) REFERENCES product_sku(id),
    CONSTRAINT fk_child_sku FOREIGN KEY (child_sku_id) REFERENCES product_sku(id)
);
COMMENT ON TABLE sku_bundle IS '组合SKU明细表';
COMMENT ON COLUMN sku_bundle.id IS '主键ID-自增';
COMMENT ON COLUMN sku_bundle.bundle_sku_id IS '组合SKU的ID（关联product_sku.id）';
COMMENT ON COLUMN sku_bundle.child_sku_id IS '子SKU的ID（必须是单SKU）';
COMMENT ON COLUMN sku_bundle.quantity IS '子SKU数量';

-- ===================== 商品链接表（铺货） =====================
CREATE TABLE product_listing (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id bigint NOT NULL,
    platform_product_id varchar(64) NOT NULL,
    main_sku_id bigint,
    brief_url varchar(2048),
    commission_public decimal(10,2) DEFAULT 0,
    commission_private decimal(10,2) DEFAULT 0,
    status smallint DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE product_listing IS '商品链接表（铺货），记录店铺中的平台商品链接';
COMMENT ON COLUMN product_listing.id IS '主键ID-自增';
COMMENT ON COLUMN product_listing.shop_id IS '所属店铺ID';
COMMENT ON COLUMN product_listing.platform_product_id IS '平台商品ID';
COMMENT ON COLUMN product_listing.main_sku_id IS '主力SKU ID（关联product_sku）';
COMMENT ON COLUMN product_listing.brief_url IS '产品PDF链接';
COMMENT ON COLUMN product_listing.commission_public IS '公开佣金';
COMMENT ON COLUMN product_listing.commission_private IS '定向佣金';
COMMENT ON COLUMN product_listing.status IS '产品链接状态：0-下架，1-在售';
COMMENT ON COLUMN product_listing.created_at IS '创建时间';
COMMENT ON COLUMN product_listing.updated_at IS '更新时间';
COMMENT ON COLUMN product_listing.deleted_at IS '软删除标记，NULL为未删除';
-- 同一店铺下平台商品ID唯一（考虑软删除）
CREATE UNIQUE INDEX uk_listing_shop_product ON product_listing(shop_id, platform_product_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_listing_shop_status ON product_listing(shop_id, status) WHERE deleted_at IS NULL;
CREATE INDEX idx_listing_main_sku ON product_listing(main_sku_id) WHERE deleted_at IS NULL;

-- ===================== 达人表 =====================
CREATE TABLE kol (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kol_id varchar(30) NOT NULL,
    kol_link varchar(2048),
    followers bigint DEFAULT 0,
    is_paid smallint DEFAULT 0,
    cooperation_fee decimal(12,2) DEFAULT 0,
    contact_info varchar(255),
    belong_bd_code varchar(10),
    status smallint DEFAULT 1,
    score decimal(3,2) DEFAULT 0,
    notes varchar(512),
    entry_time timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE kol IS '达人表（KOL）';
COMMENT ON COLUMN kol.id IS '主键ID-自增';
COMMENT ON COLUMN kol.kol_id IS '平台KOL ID（唯一）';
COMMENT ON COLUMN kol.kol_link IS '达人主页链接';
COMMENT ON COLUMN kol.followers IS '粉丝数';
COMMENT ON COLUMN kol.is_paid IS '是否付费：0-否，1-是';
COMMENT ON COLUMN kol.cooperation_fee IS '合作费';
COMMENT ON COLUMN kol.contact_info IS '联系方式';
COMMENT ON COLUMN kol.belong_bd_code IS '所属BD代号（关联bd_person.bd_code），NULL表示闲置';
COMMENT ON COLUMN kol.status IS '达人状态：1-正常，2-流失，3-黑名单';
COMMENT ON COLUMN kol.score IS '权重分';
COMMENT ON COLUMN kol.notes IS '备注';
COMMENT ON COLUMN kol.entry_time IS '达人录入时间';
COMMENT ON COLUMN kol.created_at IS '创建时间';
COMMENT ON COLUMN kol.updated_at IS '更新时间';
COMMENT ON COLUMN kol.deleted_at IS '软删除标记，NULL为未删除';
CREATE UNIQUE INDEX uk_kol_id ON kol(kol_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_kol_bd ON kol(belong_bd_code) WHERE deleted_at IS NULL;
CREATE INDEX idx_kol_status ON kol(status) WHERE deleted_at IS NULL;

-- ===================== 任务总表 =====================
CREATE TABLE task_main (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_listing_id bigint NOT NULL,
    commission decimal(10,2) NOT NULL DEFAULT 0,
    video_num int DEFAULT 0,
    deadline date,
    type smallint NOT NULL DEFAULT 0,
    budget smallint DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE task_main IS '任务总表';
COMMENT ON COLUMN task_main.id IS '主键ID-自增';
COMMENT ON COLUMN task_main.product_listing_id IS '商品链接ID（关联product_listing）';
COMMENT ON COLUMN task_main.commission IS '任务固定佣金，后续所有视频均采用该值';
COMMENT ON COLUMN task_main.video_num IS '该任务需要完成的视频数量（定制任务使用）';
COMMENT ON COLUMN task_main.deadline IS '截止日期';
COMMENT ON COLUMN task_main.type IS '任务类型：0-定制，1-公开';
COMMENT ON COLUMN task_main.budget IS '是否有预算：0-无预算，1-有预算';
COMMENT ON COLUMN task_main.created_at IS '创建时间';
COMMENT ON COLUMN task_main.updated_at IS '更新时间';
COMMENT ON COLUMN task_main.deleted_at IS '软删除标记，NULL为未删除';
CREATE INDEX idx_task_product ON task_main(product_listing_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_task_deadline ON task_main(deadline) WHERE deleted_at IS NULL;

-- ===================== 任务-BD关联表 =====================
CREATE TABLE task_bd_relation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL,
    bd_code varchar(10) NOT NULL,
    video_quantity int DEFAULT 0,
    follow_entry_time timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT uk_task_bd UNIQUE (task_id, bd_code)
);
COMMENT ON TABLE task_bd_relation IS '任务与BD关联表';
COMMENT ON COLUMN task_bd_relation.id IS '主键ID-自增';
COMMENT ON COLUMN task_bd_relation.task_id IS '关联的任务ID';
COMMENT ON COLUMN task_bd_relation.bd_code IS 'BD代号';
COMMENT ON COLUMN task_bd_relation.video_quantity IS '该BD负责的视频数量';
COMMENT ON COLUMN task_bd_relation.follow_entry_time IS '本记录录入时间';
COMMENT ON COLUMN task_bd_relation.created_at IS '创建时间';
COMMENT ON COLUMN task_bd_relation.updated_at IS '更新时间';
COMMENT ON COLUMN task_bd_relation.deleted_at IS '软删除标记，NULL为未删除';
CREATE INDEX idx_task_bd_task ON task_bd_relation(task_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_task_bd_bd ON task_bd_relation(bd_code) WHERE deleted_at IS NULL;

-- ===================== 达人筹备表 =====================
CREATE TABLE kol_bd_prepare (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL,
    kol_id varchar(32) NOT NULL,
    bd_code varchar(10) NOT NULL,
    entry_time timestamptz NOT NULL DEFAULT now(),
    status smallint DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT uk_prepare_task_kol_bd UNIQUE (task_id, kol_id, bd_code)
);
COMMENT ON TABLE kol_bd_prepare IS '达人筹备表（BD绑定达人审核）';
COMMENT ON COLUMN kol_bd_prepare.id IS '主键ID-自增';
COMMENT ON COLUMN kol_bd_prepare.task_id IS '所属任务ID';
COMMENT ON COLUMN kol_bd_prepare.kol_id IS '达人唯一ID（全局唯一绑定）';
COMMENT ON COLUMN kol_bd_prepare.bd_code IS 'BD代号';
COMMENT ON COLUMN kol_bd_prepare.entry_time IS '录入时间';
COMMENT ON COLUMN kol_bd_prepare.status IS '审核状态：0-审核中，1-通过';
COMMENT ON COLUMN kol_bd_prepare.created_at IS '创建时间';
COMMENT ON COLUMN kol_bd_prepare.updated_at IS '更新时间';
COMMENT ON COLUMN kol_bd_prepare.deleted_at IS '软删除标记，NULL为未删除';
CREATE UNIQUE INDEX uk_prepare_kol ON kol_bd_prepare(kol_id) WHERE deleted_at IS NULL;

-- ===================== BD-任务-SOP进度表 =====================
CREATE TABLE task_sop (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_bd_id bigint NOT NULL,
    task_id bigint NOT NULL,
    bd_code varchar(10) NOT NULL,
    kol_id varchar(30) NOT NULL,
    product_id bigint NOT NULL,
    product_url varchar(2048),
    status smallint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT uk_sop_task_bd_kol UNIQUE (task_id, bd_code, kol_id)
);
COMMENT ON TABLE task_sop IS 'SOP进度表，记录每个任务下BD与达人的执行状态';
COMMENT ON COLUMN task_sop.id IS '主键ID-自增';
COMMENT ON COLUMN task_sop.task_bd_id IS '关联的任务-BD关系ID（task_bd_relation.id）';
COMMENT ON COLUMN task_sop.task_id IS '所属任务ID（冗余）';
COMMENT ON COLUMN task_sop.bd_code IS 'BD代号（冗余）';
COMMENT ON COLUMN task_sop.kol_id IS '达人ID（冗余）';
COMMENT ON COLUMN task_sop.product_id IS '商品链接ID（冗余快照）';
COMMENT ON COLUMN task_sop.product_url IS '商品链接URL（冗余快照）';
COMMENT ON COLUMN task_sop.status IS 'SOP状态：0-建联，1-送样，2-回收视频，3-结束';
COMMENT ON COLUMN task_sop.created_at IS '创建时间';
COMMENT ON COLUMN task_sop.updated_at IS '更新时间';
COMMENT ON COLUMN task_sop.deleted_at IS '软删除标记，NULL为未删除';
CREATE INDEX idx_sop_task_bd ON task_sop(task_id, bd_code) WHERE deleted_at IS NULL;
CREATE INDEX idx_sop_kol ON task_sop(kol_id) WHERE deleted_at IS NULL;

-- ===================== 建联明细表 =====================
CREATE TABLE sop_contact (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_sop_id bigint NOT NULL UNIQUE,
    contact_information varchar(255),
    budget int,
    budget_status smallint DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE sop_contact IS '建联明细表（SOP建联阶段的信息）';
COMMENT ON COLUMN sop_contact.id IS '主键ID-自增';
COMMENT ON COLUMN sop_contact.task_sop_id IS '关联的task_sop.id（一对一）';
COMMENT ON COLUMN sop_contact.contact_information IS '联系方式';
COMMENT ON COLUMN sop_contact.budget IS '预算金额（整数，NULL表示无预算）';
COMMENT ON COLUMN sop_contact.budget_status IS '预算审核状态：0-无预算/待审核，1-审核通过，2-驳回';
COMMENT ON COLUMN sop_contact.created_at IS '创建时间';
COMMENT ON COLUMN sop_contact.updated_at IS '更新时间';
COMMENT ON COLUMN sop_contact.deleted_at IS '软删除标记，NULL为未删除';

-- ===================== 样品申请表 =====================
CREATE TABLE sample_application (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_sop_id bigint NOT NULL UNIQUE,
    product_listing_id bigint NOT NULL,
    address varchar(512) NOT NULL,
    quantity int DEFAULT 1,
    tracking_number varchar(50),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE sample_application IS '样品申请表';
COMMENT ON COLUMN sample_application.id IS '主键ID-自增';
COMMENT ON COLUMN sample_application.task_sop_id IS '关联的task_sop.id（一对一）';
COMMENT ON COLUMN sample_application.product_listing_id IS '关联的商品链接ID';
COMMENT ON COLUMN sample_application.address IS '收样地址';
COMMENT ON COLUMN sample_application.quantity IS '样品数量';
COMMENT ON COLUMN sample_application.tracking_number IS '快递单号（可由后续填写）';
COMMENT ON COLUMN sample_application.created_at IS '创建时间';
COMMENT ON COLUMN sample_application.updated_at IS '更新时间';
COMMENT ON COLUMN sample_application.deleted_at IS '软删除标记，NULL为未删除';

-- ===================== 视频表 =====================
CREATE TABLE video (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kol_id varchar(30) NOT NULL,
    sop_id bigint NOT NULL,
    bd_code varchar(10) NOT NULL,
    video_url varchar(2048) NOT NULL,
    score smallint,
    finish_time timestamptz,
    product_listing_id bigint NOT NULL,
    play_count bigint DEFAULT 0,
    gmv decimal(15,2) DEFAULT 0,
    commission decimal(12,2) NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE video IS '视频表（回收视频及数据）';
COMMENT ON COLUMN video.id IS '主键ID-自增';
COMMENT ON COLUMN video.kol_id IS '平台KOL ID';
COMMENT ON COLUMN video.sop_id IS '关联的task_sop.id';
COMMENT ON COLUMN video.bd_code IS 'BD代号（冗余）';
COMMENT ON COLUMN video.video_url IS '视频链接';
COMMENT ON COLUMN video.score IS '打分（0-100）';
COMMENT ON COLUMN video.finish_time IS '完成时间';
COMMENT ON COLUMN video.product_listing_id IS '商品链接ID（冗余快照）';
COMMENT ON COLUMN video.play_count IS '播放量';
COMMENT ON COLUMN video.gmv IS 'GMV成交额';
COMMENT ON COLUMN video.commission IS '佣金（取任务创建时的固定佣金快照）';
COMMENT ON COLUMN video.created_at IS '创建时间';
COMMENT ON COLUMN video.updated_at IS '更新时间';
COMMENT ON COLUMN video.deleted_at IS '软删除标记，NULL为未删除';
CREATE INDEX idx_video_sop ON video(sop_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_video_kol ON video(kol_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_video_finishtime ON video(finish_time) WHERE deleted_at IS NULL;


-- ===================== 系统用户表 =====================
CREATE TABLE sys_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL,
    password_hash varchar(255) NOT NULL,
    employee_id bigint,
    real_name varchar(64),
    status smallint DEFAULT 1,
    last_login_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE sys_user IS '系统用户表（登录认证）';
COMMENT ON COLUMN sys_user.id IS '主键ID-自增';
COMMENT ON COLUMN sys_user.username IS '登录用户名（唯一）';
COMMENT ON COLUMN sys_user.password_hash IS '密码哈希（bcrypt）';
COMMENT ON COLUMN sys_user.employee_id IS '关联员工ID，一对一，可为空（系统管理员）';
COMMENT ON COLUMN sys_user.real_name IS '真实姓名（冗余显示）';
COMMENT ON COLUMN sys_user.status IS '状态：0-禁用，1-正常';
COMMENT ON COLUMN sys_user.last_login_at IS '最后登录时间';
COMMENT ON COLUMN sys_user.created_at IS '创建时间';
COMMENT ON COLUMN sys_user.updated_at IS '更新时间';
COMMENT ON COLUMN sys_user.deleted_at IS '软删除标记，NULL为未删除';
-- 索引
CREATE UNIQUE INDEX uk_sys_user_username ON sys_user(username) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uk_sys_user_employee ON sys_user(employee_id) WHERE deleted_at IS NULL AND employee_id IS NOT NULL;

-- ===================== 角色表 =====================
CREATE TABLE sys_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code varchar(30) NOT NULL,
    role_name varchar(50) NOT NULL,
    remark varchar(255),
    is_system smallint DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE sys_role IS '角色表';
COMMENT ON COLUMN sys_role.id IS '主键ID-自增';
COMMENT ON COLUMN sys_role.role_code IS '角色编码（唯一，如 ADMIN、BD_MANAGER）';
COMMENT ON COLUMN sys_role.role_name IS '角色名称';
COMMENT ON COLUMN sys_role.remark IS '备注';
COMMENT ON COLUMN sys_role.is_system IS '是否系统内置角色（0-否，1-是），内置角色不可删除';
COMMENT ON COLUMN sys_role.created_at IS '创建时间';
COMMENT ON COLUMN sys_role.updated_at IS '更新时间';
COMMENT ON COLUMN sys_role.deleted_at IS '软删除标记，NULL为未删除';
CREATE UNIQUE INDEX uk_sys_role_code ON sys_role(role_code) WHERE deleted_at IS NULL;

-- ===================== 权限/菜单表 =====================
CREATE TABLE sys_permission (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint DEFAULT 0,
    perm_code varchar(64) NOT NULL,
    perm_name varchar(50) NOT NULL,
    perm_type smallint DEFAULT 1,
    icon varchar(64),
    sort_order int DEFAULT 0,
    status smallint DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
COMMENT ON TABLE sys_permission IS '权限/菜单表（树形结构）';
COMMENT ON COLUMN sys_permission.id IS '主键ID-自增';
COMMENT ON COLUMN sys_permission.parent_id IS '父级权限ID，0表示顶级菜单';
COMMENT ON COLUMN sys_permission.perm_code IS '权限标识（唯一），如 product:view';
COMMENT ON COLUMN sys_permission.perm_name IS '权限名称，如“商品查看”';
COMMENT ON COLUMN sys_permission.perm_type IS '类型：1-菜单，2-按钮，3-接口';
COMMENT ON COLUMN sys_permission.icon IS '菜单图标';
COMMENT ON COLUMN sys_permission.sort_order IS '排序序号';
COMMENT ON COLUMN sys_permission.status IS '状态：0-禁用，1-正常';
COMMENT ON COLUMN sys_permission.created_at IS '创建时间';
COMMENT ON COLUMN sys_permission.updated_at IS '更新时间';
COMMENT ON COLUMN sys_permission.deleted_at IS '软删除标记，NULL为未删除';
CREATE UNIQUE INDEX uk_sys_permission_code ON sys_permission(perm_code) WHERE deleted_at IS NULL;
CREATE INDEX idx_sys_permission_parent ON sys_permission(parent_id) WHERE deleted_at IS NULL;

-- ===================== 用户-角色关联表 =====================
CREATE TABLE sys_user_role (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);
COMMENT ON TABLE sys_user_role IS '用户-角色关联表';
COMMENT ON COLUMN sys_user_role.user_id IS '用户ID（关联sys_user.id）';
COMMENT ON COLUMN sys_user_role.role_id IS '角色ID（关联sys_role.id）';

-- ===================== 角色-权限关联表 =====================
CREATE TABLE sys_role_permission (
    role_id bigint NOT NULL,
    perm_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (role_id, perm_id)
);
COMMENT ON TABLE sys_role_permission IS '角色-权限关联表';
COMMENT ON COLUMN sys_role_permission.role_id IS '角色ID（关联sys_role.id）';
COMMENT ON COLUMN sys_role_permission.perm_id IS '权限ID（关联sys_permission.id）';


-- 初始化超级管理员
-- 角色
INSERT INTO sys_role (role_code, role_name, is_system) VALUES ('ADMIN', '超级管理员', 1);

-- 默认管理员用户（密码需用 bcrypt 加密，这里示例）
INSERT INTO sys_user (username, password_hash, real_name, employee_id)
VALUES ('admin', '$2a$10$...替换为真实密文', '系统管理员', NULL);

-- 赋予角色
INSERT INTO sys_user_role (user_id, role_id) VALUES (1, 1);

-- 将全部权限赋给 ADMIN
INSERT INTO sys_role_permission (role_id, perm_id)
SELECT 1, id FROM sys_permission;
